### ISSUE TITLE
Correct label

### ISSUE THREAD

**Issue by pwalczysko** [openmicroscopy/virtual-microscope#11]
On ray ,Image ID: 	1068  under Dermatology, the label of one of the ROIs says ``Full thinkness epidermis forms....`` - this should be ``Full thickness epidermis....`` (replace ``thinkness``)

**Comment by aleksandra-tarkowska** [comment]
![firefoxscreensnapz008](https://cloud.githubusercontent.com/assets/1065155/10164680/c7f81e30-66b2-11e5-94f7-b165d1386f10.png)
fixed on production
