### ISSUE TITLE
Attachments do not play 

### ISSUE THREAD

**Issue by pwalczysko** [openmicroscopy/virtual-microscope#8]
Three attachments on ray on image ID 321 should be possible to open by the user (which is not the owner of them). This fails.  
The similar setup (owner of a group and also of the image attaches a file attachment onto the image, then another user, non owner of the group and non owner of the image tries to open it in read-only group).  The action proceeds fine on trout merge. This means this is either a specific bug for the type of attachment ? Or the server ? Or virtual microscope ?

**Comment by pwalczysko** [comment]
Also another independent test on demo server showed that there is no problem with opening attachments which you don't own in Web in 5.1.3

**Comment by pwalczysko** [comment]
Further info: the problem is not specific to the type of the file attachment. A simple pdf does not download either. After some more investigation with @will-moore this looks like the clicking onto the attachment does not give you any link to bring you to (see below). Possible candidate might be disabling of downloads on the server ? (the ray server, as noted above, trout and demo servers work fine in this sense)

![screen shot 2015-08-04 at 17 10 08](https://cloud.githubusercontent.com/assets/2478303/9065840/02ae85ae-3acc-11e5-87b3-562147ff3707.png)

**Comment by aleksandra-tarkowska** [comment]
@pwalczysko that is because we set up download restriction for every component to not allow to download raw data. I will review that to see if is possible to exclude annotations

**Comment by pwalczysko** [comment]
@aleksandra-tarkowska +1

**Comment by aleksandra-tarkowska** [comment]
It is not a bug is just configure issue. Thak you for picking it up

**Comment by pwalczysko** [comment]
Fixed on ray as of today
